name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Build plugin
        run: |
          cd packages/plugin
          pnpm install
          pnpm run build
        env:
          PNPM_DEBUG: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          cd packages/plugin
          gh release create "$tag" \
            --title="$tag" \
            main.js manifest.json styles.css

      - name: Deploy preview
        run: |
          pnpm install
          pnpm netlify deploy --filter packages/preview --prod
        env:
          NETLIFY_SITE_ID: e85256f4-f552-41d1-abd8-c745ef74c3fc
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
